# Generated by CLAUDE

locals {
  create_authorizer = var.authorizer != null
}

resource "aws_apigatewayv2_authorizer" "this" {
  count = local.create_authorizer ? 1 : 0

  api_id           = aws_apigatewayv2_api.this.id
  authorizer_type  = "JWT"
  name             = var.authorizer.name
  identity_sources = var.authorizer.identity_sources

  jwt_configuration {
    issuer   = var.authorizer.issuer
    audience = var.authorizer.audience
  }
}
