# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

# --- Lambda function ---

module "order_processor" {
  source = "../../modules/lambda-function"

  function_name = "order-processor"

  zip = {
    filename = "dist/order-processor.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  memory_size = 512
  timeout     = 30

  environment_variables = {
    TABLE_NAME  = "orders"
    BUCKET_NAME = "order-attachments"
  }

  tags = {
    Team = "platform"
  }
}

# --- API Gateway trigger ---

module "order_processor_api" {
  source = "../../modules/lambda-trigger-apigw"

  function_name = module.order_processor.function_name
  function_arn  = module.order_processor.function_arn
  invoke_arn    = module.order_processor.invoke_arn

  routes = [
    "GET /orders",
    "POST /orders",
  ]

  tags = {
    Team = "platform"
  }
}

# --- DynamoDB stream trigger ---

resource "aws_dynamodb_table" "orders" {
  name             = "orders"
  billing_mode     = "PAY_PER_REQUEST"
  hash_key         = "id"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "id"
    type = "S"
  }
}

module "order_processor_stream" {
  source = "../../modules/lambda-trigger-dynamodb"

  function_name = module.order_processor.function_name
  function_arn  = module.order_processor.function_arn
  role_name     = module.order_processor.role_name

  stream_arn = aws_dynamodb_table.orders.stream_arn
  batch_size = 50

  filter_criteria = [
    { pattern = jsonencode({ eventName = ["INSERT"] }) }
  ]
}

# --- S3 trigger ---

resource "aws_s3_bucket" "attachments" {
  bucket = "order-attachments"
  # Allow `terraform destroy` to remove the bucket even when objects remain.
  force_destroy = true
}

module "order_processor_s3" {
  source = "../../modules/lambda-trigger-s3"

  function_name = module.order_processor.function_name
  function_arn  = module.order_processor.function_arn

  bucket_id  = aws_s3_bucket.attachments.id
  bucket_arn = aws_s3_bucket.attachments.arn
  events     = ["s3:ObjectCreated:*"]

  filter_prefix = "uploads/"
}

# --- Outputs ---

output "api_endpoint" {
  value = module.order_processor_api.api_endpoint
}
