# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

module "api_service" {
  source = "../../modules/lambda-function"

  function_name = "api-service"

  image = {
    uri = "123456789012.dkr.ecr.us-east-1.amazonaws.com/api-service:latest"
  }

  memory_size  = 1024
  timeout      = 30
  architecture = "arm64"

  environment_variables = {
    DATABASE_URL = "postgres://..."
    LOG_LEVEL    = "info"
  }

  tags = {
    Team        = "platform"
    Environment = "prod"
  }
}

output "function_arn" {
  value = module.api_service.function_arn
}
