# Generated by CLAUDE

resource "aws_lambda_event_source_mapping" "this" {
  event_source_arn = var.queue_arn
  function_name    = var.function_arn
  batch_size       = var.batch_size

  maximum_batching_window_in_seconds = var.maximum_batching_window_in_seconds
  function_response_types            = var.report_batch_item_failures ? ["ReportBatchItemFailures"] : []

  dynamic "filter_criteria" {
    for_each = length(var.filter_criteria) > 0 ? [1] : []

    content {
      dynamic "filter" {
        for_each = var.filter_criteria

        content {
          pattern = filter.value.pattern
        }
      }
    }
  }

  depends_on = [
    aws_iam_role_policy_attachment.queue_read,
  ]
}

data "aws_iam_policy_document" "queue_read" {
  statement {
    actions = [
      "sqs:ReceiveMessage",
      "sqs:DeleteMessage",
      "sqs:GetQueueAttributes",
    ]

    resources = [var.queue_arn]
  }
}

resource "aws_iam_policy" "queue_read" {
  name   = "${var.function_name}-sqs-queue-read"
  policy = data.aws_iam_policy_document.queue_read.json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "queue_read" {
  role       = var.role_name
  policy_arn = aws_iam_policy.queue_read.arn
}
