# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "role_name" {
  description = "Name of the Lambda execution role (for attaching SQS read policy)"
  type        = string
}

variable "queue_arn" {
  description = "ARN of the SQS queue"
  type        = string
}

# --- Optional ---

variable "batch_size" {
  description = "Maximum number of messages per batch"
  type        = number
  default     = 10
}

variable "maximum_batching_window_in_seconds" {
  description = "Maximum time to gather messages before invoking the function"
  type        = number
  default     = 0
}

variable "report_batch_item_failures" {
  description = "Enable partial batch failure reporting. When true, the function can report individual message failures."
  type        = bool
  default     = false
}

variable "filter_criteria" {
  description = "Event filtering criteria for the event source mapping"
  type = list(object({
    pattern = string
  }))
  default = []
}

variable "tags" {
  description = "Map of tags to apply to all resources"
  type        = map(string)
  default     = {}
}
