# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

# Example 1: Recurring schedule with timezone
module "scheduled_task" {
  source = "../../modules/lambda-function"

  function_name = "daily-report"

  zip = {
    filename = "dist/daily-report.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  tags = {
    Team = "platform"
  }
}

module "daily_report_schedule" {
  source = "../../modules/lambda-trigger-scheduler"

  function_name = module.scheduled_task.function_name
  function_arn  = module.scheduled_task.function_arn

  schedule_name       = "daily-report-9am"
  description         = "Generate daily report at 9 AM Eastern"
  schedule_expression = "cron(0 9 * * ? *)"
  timezone            = "America/New_York"

  # Allow execution within 15 minute window
  flexible_time_window = 15

  input = jsonencode({
    report_type = "daily"
  })
}

# Example 2: One-time schedule
module "one_time_task" {
  source = "../../modules/lambda-function"

  function_name = "migration-task"

  zip = {
    filename = "dist/migration.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  tags = {
    Team = "platform"
  }
}

module "one_time_migration" {
  source = "../../modules/lambda-trigger-scheduler"

  function_name = module.one_time_task.function_name
  function_arn  = module.one_time_task.function_arn

  schedule_name       = "run-migration-once"
  description         = "One-time migration scheduled for specific date"
  schedule_expression = "at(2026-04-01T02:00:00)"
  timezone            = "UTC"
}

# Example 3: Rate-based schedule with retry policy
module "health_check" {
  source = "../../modules/lambda-function"

  function_name = "health-check"

  zip = {
    filename = "dist/health-check.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  tags = {
    Team = "platform"
  }
}

module "health_check_schedule" {
  source = "../../modules/lambda-trigger-scheduler"

  function_name = module.health_check.function_name
  function_arn  = module.health_check.function_arn

  schedule_name       = "health-check-every-5min"
  schedule_expression = "rate(5 minutes)"

  retry_policy = {
    maximum_retry_attempts       = 3
    maximum_event_age_in_seconds = 300
  }
}

output "daily_report_schedule_arn" {
  value = module.daily_report_schedule.schedule_arn
}

output "one_time_schedule_arn" {
  value = module.one_time_migration.schedule_arn
}

output "health_check_schedule_arn" {
  value = module.health_check_schedule.schedule_arn
}
