# Generated by CLAUDE

locals {
  trigger_set = toset(var.triggers)
}

resource "aws_cognito_user_pool_lambda_config" "this" {
  user_pool_id = var.user_pool_id

  pre_sign_up                    = contains(local.trigger_set, "pre_sign_up") ? var.function_arn : null
  post_confirmation              = contains(local.trigger_set, "post_confirmation") ? var.function_arn : null
  pre_authentication             = contains(local.trigger_set, "pre_authentication") ? var.function_arn : null
  post_authentication            = contains(local.trigger_set, "post_authentication") ? var.function_arn : null
  pre_token_generation           = contains(local.trigger_set, "pre_token_generation") ? var.function_arn : null
  custom_message                 = contains(local.trigger_set, "custom_message") ? var.function_arn : null
  define_auth_challenge          = contains(local.trigger_set, "define_auth_challenge") ? var.function_arn : null
  create_auth_challenge          = contains(local.trigger_set, "create_auth_challenge") ? var.function_arn : null
  verify_auth_challenge_response = contains(local.trigger_set, "verify_auth_challenge_response") ? var.function_arn : null
  user_migration                 = contains(local.trigger_set, "user_migration") ? var.function_arn : null

  depends_on = [
    aws_lambda_permission.this,
  ]
}

resource "aws_lambda_permission" "this" {
  statement_id  = "AllowCognitoInvoke-${var.function_name}"
  action        = "lambda:InvokeFunction"
  function_name = var.function_arn
  principal     = "cognito-idp.amazonaws.com"
  source_arn    = "arn:aws:cognito-idp:*:*:userpool/${var.user_pool_id}"
}
