# Generated by CLAUDE
#
# Permission-only module: grants Cognito permission to invoke a Lambda.
# The actual trigger wiring must be done in the aws_cognito_user_pool
# resource's lambda_config block - AWS doesn't support standalone trigger
# attachment for Cognito.

resource "aws_lambda_permission" "this" {
  statement_id  = "AllowCognitoInvoke-${var.function_name}"
  action        = "lambda:InvokeFunction"
  function_name = var.function_arn
  principal     = "cognito-idp.amazonaws.com"
  source_arn    = "arn:aws:cognito-idp:*:*:userpool/${var.user_pool_id}"
}
