# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "user_pool_id" {
  description = "ID of the Cognito User Pool"
  type        = string
}

variable "triggers" {
  description = "List of Cognito trigger types to wire to this Lambda (e.g. [\"pre_sign_up\", \"post_confirmation\"])"
  type        = list(string)

  validation {
    condition = alltrue([
      for t in var.triggers : contains([
        "pre_sign_up",
        "post_confirmation",
        "pre_authentication",
        "post_authentication",
        "pre_token_generation",
        "custom_message",
        "define_auth_challenge",
        "create_auth_challenge",
        "verify_auth_challenge_response",
        "user_migration",
      ], t)
    ])
    error_message = "Each trigger must be one of: pre_sign_up, post_confirmation, pre_authentication, post_authentication, pre_token_generation, custom_message, define_auth_challenge, create_auth_challenge, verify_auth_challenge_response, user_migration."
  }
}

# --- Optional ---

variable "tags" {
  description = "Map of tags (accepted for interface consistency)"
  type        = map(string)
  default     = {}
}
