# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "user_pool_id" {
  description = "ID of the Cognito User Pool"
  type        = string
}
