# Generated by CLAUDE
#
# This example shows how to reference the modules from a remote GitHub repository.
# Replace "your-org/terraform-lambdas" with your actual repository path.
# Always pin to a tag (?ref=v1.0.0) for reproducibility.

provider "aws" {
  region = "us-east-1"
}

module "order_api" {
  source = "github.com/your-org/terraform-lambdas//modules/lambda-function?ref=v1.0.0"

  function_name = "order-api"

  zip = {
    filename = "dist/order-api.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  memory_size = 512
  timeout     = 30

  tags = {
    Team = "platform"
  }
}

module "order_api_trigger" {
  source = "github.com/your-org/terraform-lambdas//modules/lambda-trigger-apigw?ref=v1.0.0"

  function_name = module.order_api.function_name
  function_arn  = module.order_api.function_arn
  invoke_arn    = module.order_api.invoke_arn

  routes = [
    "GET /orders",
    "POST /orders",
  ]

  tags = {
    Team = "platform"
  }
}

output "api_endpoint" {
  value = module.order_api_trigger.api_endpoint
}
