# Generated by CLAUDE

locals {
  role_name         = local.create_role ? aws_iam_role.this[0].name : regex(".*role/(.+)$", var.existing_role_arn)[0]
  attach_log_policy = local.create_role || var.attach_log_policy
}

# --- Execution role (created when existing_role_arn is null) ---

data "aws_iam_policy_document" "assume_role" {
  count = local.create_role ? 1 : 0

  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "this" {
  count = local.create_role ? 1 : 0

  name               = "${var.function_name}-execution-role"
  assume_role_policy = data.aws_iam_policy_document.assume_role[0].json
  tags               = var.tags
}

# --- CloudWatch Logs policy ---

data "aws_iam_policy_document" "logs" {
  count = local.attach_log_policy ? 1 : 0

  statement {
    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]

    resources = [
      "${aws_cloudwatch_log_group.this.arn}",
      "${aws_cloudwatch_log_group.this.arn}:*",
    ]
  }
}

resource "aws_iam_policy" "logs" {
  count = local.attach_log_policy ? 1 : 0

  name   = "${var.function_name}-logs"
  policy = data.aws_iam_policy_document.logs[0].json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "logs" {
  count = local.attach_log_policy ? 1 : 0

  role       = local.role_name
  policy_arn = aws_iam_policy.logs[0].arn
}

# --- VPC access policy (when Lambda is in a VPC) ---

resource "aws_iam_role_policy_attachment" "vpc" {
  count = local.has_vpc ? 1 : 0

  role       = local.role_name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}

# --- Additional policies provided by caller ---

resource "aws_iam_role_policy_attachment" "additional" {
  for_each = toset(var.additional_policy_arns)

  role       = local.role_name
  policy_arn = each.value
}
