# Generated by CLAUDE

# --- Execution role ---

data "aws_iam_policy_document" "assume_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "this" {
  name               = "${var.function_name}-execution-role"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
  tags               = var.tags
}

# --- CloudWatch Logs policy ---

data "aws_iam_policy_document" "logs" {
  statement {
    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]

    resources = [
      "${aws_cloudwatch_log_group.this.arn}",
      "${aws_cloudwatch_log_group.this.arn}:*",
    ]
  }
}

resource "aws_iam_policy" "logs" {
  name   = "${var.function_name}-logs"
  policy = data.aws_iam_policy_document.logs.json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "logs" {
  role       = aws_iam_role.this.name
  policy_arn = aws_iam_policy.logs.arn
}

# --- VPC access policy (when Lambda is in a VPC) ---

resource "aws_iam_role_policy_attachment" "vpc" {
  count = local.has_vpc ? 1 : 0

  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}

# --- Additional policies provided by caller ---

resource "aws_iam_role_policy_attachment" "additional" {
  count = length(var.additional_policy_arns)

  role       = aws_iam_role.this.name
  policy_arn = var.additional_policy_arns[count.index]
}

# --- EFS access policy (when an EFS file system is mounted) ---

data "aws_iam_policy_document" "efs" {
  count = local.has_efs ? 1 : 0

  statement {
    actions = [
      "elasticfilesystem:ClientMount",
      "elasticfilesystem:ClientWrite",
      "elasticfilesystem:ClientRootAccess",
    ]

    # AWS does not accept an access-point ARN as the IAM resource for
    # elasticfilesystem:Client* actions; scope to the access point via condition instead.
    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "elasticfilesystem:AccessPointArn"
      values   = [var.efs_config.access_point_arn]
    }
  }
}

resource "aws_iam_policy" "efs" {
  count = local.has_efs ? 1 : 0

  name   = "${var.function_name}-efs"
  policy = data.aws_iam_policy_document.efs[0].json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "efs" {
  count = local.has_efs ? 1 : 0

  role       = aws_iam_role.this.name
  policy_arn = aws_iam_policy.efs[0].arn
}
