# Generated by CLAUDE

resource "aws_lambda_permission" "this" {
  statement_id  = "AllowSNSInvoke-${var.function_name}"
  action        = "lambda:InvokeFunction"
  function_name = var.function_arn
  principal     = "sns.amazonaws.com"
  source_arn    = var.topic_arn
}

resource "aws_sns_topic_subscription" "this" {
  topic_arn = var.topic_arn
  protocol  = "lambda"
  endpoint  = var.function_arn

  filter_policy       = var.filter_policy
  filter_policy_scope = var.filter_policy != null ? var.filter_policy_scope : null

  depends_on = [
    aws_lambda_permission.this,
  ]
}
