# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "topic_arn" {
  description = "ARN of the SNS topic"
  type        = string
}

# --- Optional ---

variable "filter_policy" {
  description = "JSON-encoded SNS subscription filter policy. Set to null (default) for no filtering."
  type        = string
  default     = null
}

variable "filter_policy_scope" {
  description = "Scope of the filter policy: MessageAttributes (default) or MessageBody"
  type        = string
  default     = "MessageAttributes"
}

variable "tags" {
  description = "Map of tags (accepted for interface consistency)"
  type        = map(string)
  default     = {}
}
