# Generated by CLAUDE

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = aws_s3_bucket.this.id
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = aws_s3_bucket.this.arn
}

output "distribution_id" {
  description = "ID of the CloudFront distribution"
  value       = aws_cloudfront_distribution.this.id
}

output "distribution_domain_name" {
  description = "Domain name of the CloudFront distribution (*.cloudfront.net)"
  value       = aws_cloudfront_distribution.this.domain_name
}

output "site_url" {
  description = "URL of the site (custom domain if configured, otherwise CloudFront domain)"
  value       = local.create_domain ? "https://${var.custom_domain.domain_name}" : "https://${aws_cloudfront_distribution.this.domain_name}"
}
