# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

resource "aws_sqs_queue" "tasks" {
  name = "task-queue"
}

module "task_processor" {
  source = "../../modules/lambda-function"

  function_name = "task-processor"

  zip = {
    filename = "dist/task-processor.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  tags = {
    Team = "platform"
  }
}

module "task_processor_sqs" {
  source = "../../modules/lambda-trigger-sqs"

  function_name = module.task_processor.function_name
  function_arn  = module.task_processor.function_arn
  role_name     = module.task_processor.role_name
  queue_arn     = aws_sqs_queue.tasks.arn

  batch_size                         = 5
  maximum_batching_window_in_seconds = 30
  report_batch_item_failures         = true

  # Optional: only process specific message types
  filter_criteria = [
    {
      pattern = jsonencode({
        body = {
          type = ["order"]
        }
      })
    }
  ]
}

output "event_source_mapping_id" {
  value = module.task_processor_sqs.event_source_mapping_id
}
