# Generated by CLAUDE

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

resource "aws_scheduler_schedule" "this" {
  name        = var.schedule_name
  group_name  = var.schedule_group_name
  description = var.description

  schedule_expression          = var.schedule_expression
  schedule_expression_timezone = var.timezone
  state                        = var.enabled ? "ENABLED" : "DISABLED"

  start_date = var.start_date
  end_date   = var.end_date

  flexible_time_window {
    mode                      = var.flexible_time_window > 0 ? "FLEXIBLE" : "OFF"
    maximum_window_in_minutes = var.flexible_time_window > 0 ? var.flexible_time_window : null
  }

  target {
    arn      = var.function_arn
    role_arn = aws_iam_role.scheduler.arn
    input    = var.input

    dynamic "retry_policy" {
      for_each = var.retry_policy != null ? [var.retry_policy] : []
      content {
        maximum_event_age_in_seconds = retry_policy.value.maximum_event_age_in_seconds
        maximum_retry_attempts       = retry_policy.value.maximum_retry_attempts
      }
    }

    dynamic "dead_letter_config" {
      for_each = var.dead_letter_arn != null ? [1] : []
      content {
        arn = var.dead_letter_arn
      }
    }
  }

  kms_key_arn = var.kms_key_arn
}
