# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "schedule_name" {
  description = "Name of the schedule"
  type        = string
}

variable "schedule_expression" {
  description = "Schedule expression: rate(5 minutes), cron(0 12 * * ? *), or at(2024-01-01T00:00:00) for one-time"
  type        = string
}

# --- Optional ---

variable "description" {
  description = "Description of the schedule"
  type        = string
  default     = null
}

variable "schedule_group_name" {
  description = "Name of the schedule group (defaults to 'default')"
  type        = string
  default     = "default"
}

variable "timezone" {
  description = "Timezone for the schedule (e.g., 'America/New_York', 'Europe/Paris'). Defaults to UTC."
  type        = string
  default     = "UTC"
}

variable "flexible_time_window" {
  description = "Flexible time window in minutes. Set to 0 for OFF (exact time)."
  type        = number
  default     = 0
}

variable "start_date" {
  description = "Start date for the schedule in ISO 8601 format (e.g., 2024-01-01T00:00:00Z)"
  type        = string
  default     = null
}

variable "end_date" {
  description = "End date for the schedule in ISO 8601 format (e.g., 2024-12-31T23:59:59Z)"
  type        = string
  default     = null
}

variable "enabled" {
  description = "Whether the schedule is enabled"
  type        = bool
  default     = true
}

variable "input" {
  description = "JSON-encoded input to pass to the Lambda function"
  type        = string
  default     = null
}

variable "retry_policy" {
  description = "Retry policy configuration"
  type = object({
    maximum_event_age_in_seconds = optional(number, 86400)
    maximum_retry_attempts       = optional(number, 185)
  })
  default = null
}

variable "dead_letter_arn" {
  description = "ARN of the SQS queue for dead-letter (failed invocations)"
  type        = string
  default     = null
}

variable "kms_key_arn" {
  description = "ARN of the KMS key to encrypt the schedule"
  type        = string
  default     = null
}

variable "tags" {
  description = "Map of tags to apply to resources"
  type        = map(string)
  default     = {}
}
