# Generated by CLAUDE

data "aws_iam_policy_document" "stream_read" {
  statement {
    actions = [
      "dynamodb:GetRecords",
      "dynamodb:GetShardIterator",
      "dynamodb:DescribeStream",
      "dynamodb:ListStreams",
    ]

    resources = [var.stream_arn]
  }
}

resource "aws_iam_policy" "stream_read" {
  name   = "${var.function_name}-dynamodb-stream-read"
  policy = data.aws_iam_policy_document.stream_read.json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "stream_read" {
  role       = var.role_name
  policy_arn = aws_iam_policy.stream_read.arn
}
