# Generated by CLAUDE

resource "aws_lambda_event_source_mapping" "this" {
  event_source_arn  = var.stream_arn
  function_name     = var.function_arn
  starting_position = var.starting_position
  batch_size        = var.batch_size

  maximum_batching_window_in_seconds = var.maximum_batching_window_in_seconds
  parallelization_factor             = var.parallelization_factor

  dynamic "filter_criteria" {
    for_each = length(var.filter_criteria) > 0 ? [1] : []

    content {
      dynamic "filter" {
        for_each = var.filter_criteria

        content {
          pattern = filter.value.pattern
        }
      }
    }
  }

  depends_on = [
    aws_iam_role_policy_attachment.stream_read,
  ]
}
