# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "role_name" {
  description = "Name of the Lambda execution role (for attaching stream read policy)"
  type        = string
}

variable "stream_arn" {
  description = "ARN of the DynamoDB stream"
  type        = string
}

# --- Optional ---

variable "starting_position" {
  description = "Position in the stream to start reading (LATEST or TRIM_HORIZON)"
  type        = string
  default     = "LATEST"
}

variable "batch_size" {
  description = "Maximum number of records per batch"
  type        = number
  default     = 100
}

variable "maximum_batching_window_in_seconds" {
  description = "Maximum time to gather records before invoking the function"
  type        = number
  default     = 0
}

variable "parallelization_factor" {
  description = "Number of batches to process concurrently from each shard"
  type        = number
  default     = 1
}

variable "filter_criteria" {
  description = "Event filtering criteria for the event source mapping"
  type = list(object({
    pattern = string
  }))
  default = []
}

variable "tags" {
  description = "Map of tags to apply to all resources"
  type        = map(string)
  default     = {}
}
