# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

module "website" {
  source = "../../modules/s3-static-site"

  site_name = "my-app-website"

  # SPA mode is enabled by default — all routes return index.html
  # Set spa_mode = false for multi-page sites or documentation

  custom_domain = {
    domain_name     = "www.example.com"
    hosted_zone_id  = "Z0123456789ABCDEF"
    certificate_arn = "arn:aws:acm:us-east-1:123456789012:certificate/abcd-1234-efgh-5678"
  }

  tags = {
    Team = "frontend"
  }
}

output "site_url" {
  value = module.website.site_url
}

output "bucket_name" {
  value = module.website.bucket_name
}

output "distribution_id" {
  value = module.website.distribution_id
}
