# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

resource "aws_sns_topic" "orders" {
  name = "order-events"
}

module "order_handler" {
  source = "../../modules/lambda-function"

  function_name = "order-handler"

  zip = {
    filename = "dist/order-handler.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  tags = {
    Team = "platform"
  }
}

module "order_handler_sns" {
  source = "../../modules/lambda-trigger-sns"

  function_name = module.order_handler.function_name
  function_arn  = module.order_handler.function_arn

  topic_arn = aws_sns_topic.orders.arn

  # Optional: only receive specific event types
  filter_policy = jsonencode({
    event_type = ["order_placed", "order_shipped"]
  })
}

output "subscription_arn" {
  value = module.order_handler_sns.subscription_arn
}
