# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

module "hello_world" {
  source = "../../modules/lambda-function"

  function_name = "hello-world"

  zip = {
    filename = "dist/hello-world.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  tags = {
    Environment = "dev"
  }
}

output "function_arn" {
  value = module.hello_world.function_arn
}
