# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

data "aws_route53_zone" "main" {
  name = "example.com"
}

data "aws_acm_certificate" "wildcard" {
  domain   = "*.example.com"
  statuses = ["ISSUED"]
}

module "order_api" {
  source = "../../modules/lambda-function"

  function_name = "order-api"

  zip = {
    filename = "dist/order-api.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  memory_size  = 512
  timeout      = 30
  architecture = "arm64"

  environment_variables = {
    TABLE_NAME = "orders"
    STAGE      = "prod"
  }

  tags = {
    Team        = "platform"
    Environment = "prod"
  }
}

module "order_api_trigger" {
  source = "../../modules/lambda-trigger-apigw"

  function_name = module.order_api.function_name
  function_arn  = module.order_api.function_arn
  invoke_arn    = module.order_api.invoke_arn

  routes = [
    "GET /orders",
    "POST /orders",
    "GET /orders/{id}",
    "DELETE /orders/{id}",
  ]

  custom_domain = {
    domain_name     = "api.example.com"
    hosted_zone_id  = data.aws_route53_zone.main.zone_id
    certificate_arn = data.aws_acm_certificate.wildcard.arn
  }

  tags = {
    Team        = "platform"
    Environment = "prod"
  }
}

output "api_endpoint" {
  value = module.order_api_trigger.api_endpoint
}

output "custom_domain_url" {
  value = module.order_api_trigger.custom_domain_url
}
