# Generated by CLAUDE

resource "aws_lambda_permission" "this" {
  statement_id  = "AllowS3Invoke-${var.function_name}"
  action        = "lambda:InvokeFunction"
  function_name = var.function_arn
  principal     = "s3.amazonaws.com"
  source_arn    = var.bucket_arn
}

resource "aws_s3_bucket_notification" "this" {
  bucket = var.bucket_id

  # Each filter combination requires its own lambda_function block
  dynamic "lambda_function" {
    for_each = var.filters
    content {
      lambda_function_arn = var.function_arn
      events              = var.events
      filter_prefix       = lambda_function.value.prefix
      filter_suffix       = lambda_function.value.suffix
    }
  }

  depends_on = [
    aws_lambda_permission.this,
  ]
}
