# Generated by CLAUDE

resource "aws_lambda_permission" "this" {
  statement_id  = "AllowS3Invoke-${var.function_name}"
  action        = "lambda:InvokeFunction"
  function_name = var.function_arn
  principal     = "s3.amazonaws.com"
  source_arn    = var.bucket_arn
}

resource "aws_s3_bucket_notification" "this" {
  bucket = var.bucket_id

  lambda_function {
    lambda_function_arn = var.function_arn
    events              = var.events
    filter_prefix       = var.filter_prefix
    filter_suffix       = var.filter_suffix
  }

  depends_on = [
    aws_lambda_permission.this,
  ]
}
