# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "bucket_id" {
  description = "ID of the S3 bucket"
  type        = string
}

variable "bucket_arn" {
  description = "ARN of the S3 bucket"
  type        = string
}

variable "events" {
  description = "List of S3 event types (e.g. [\"s3:ObjectCreated:*\"])"
  type        = list(string)
}

# --- Optional ---

variable "filter_prefix" {
  description = "Object key prefix filter"
  type        = string
  default     = null
}

variable "filter_suffix" {
  description = "Object key suffix filter"
  type        = string
  default     = null
}

variable "tags" {
  description = "Map of tags (accepted for interface consistency)"
  type        = map(string)
  default     = {}
}
