# Generated by CLAUDE

# --- Required ---

variable "function_name" {
  description = "Name of the Lambda function (used for resource naming)"
  type        = string
}

variable "function_arn" {
  description = "ARN of the Lambda function"
  type        = string
}

variable "bucket_id" {
  description = "ID of the S3 bucket"
  type        = string
}

variable "bucket_arn" {
  description = "ARN of the S3 bucket"
  type        = string
}

variable "events" {
  description = "List of S3 event types (e.g. [\"s3:ObjectCreated:*\"])"
  type        = list(string)
}

# --- Optional ---

variable "filters" {
  description = "List of filter objects with prefix and/or suffix"
  type = list(object({
    prefix = optional(string)
    suffix = optional(string)
  }))
  default = [{}]  # Single empty filter = no filtering
}

variable "tags" {
  description = "Map of tags (accepted for interface consistency)"
  type        = map(string)
  default     = {}
}
