# Generated by CLAUDE

provider "aws" {
  region = "us-east-1"
}

resource "aws_cognito_user_pool" "main" {
  name = "my-app-users"
}

resource "aws_cognito_user_pool_client" "main" {
  name         = "my-app-client"
  user_pool_id = aws_cognito_user_pool.main.id

  explicit_auth_flows = [
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]
}

module "api_handler" {
  source = "../../modules/lambda-function"

  function_name = "my-api-handler"

  zip = {
    filename = "dist/api-handler.zip"
    runtime  = "python3.12"
    handler  = "main.handler"
  }

  tags = {
    Team = "platform"
  }
}

module "api_gateway" {
  source = "../../modules/lambda-trigger-apigw"

  function_name = module.api_handler.function_name
  function_arn  = module.api_handler.function_arn
  invoke_arn    = module.api_handler.invoke_arn

  routes = [
    "GET /users",
    "POST /users",
    "GET /users/{id}",
  ]

  authorizer = {
    name     = "cognito"
    issuer   = "https://cognito-idp.us-east-1.amazonaws.com/${aws_cognito_user_pool.main.id}"
    audience = [aws_cognito_user_pool_client.main.id]
  }

  tags = {
    Team = "platform"
  }
}

output "api_endpoint" {
  value = module.api_gateway.api_endpoint
}

output "user_pool_id" {
  value = aws_cognito_user_pool.main.id
}

output "client_id" {
  value = aws_cognito_user_pool_client.main.id
}
